# name: Build check (Backend)

# on:
#   pull_request:
#     branches:
#       - "*"

# jobs:
#   backend-build:
#     name: Build Backend
#     runs-on: [self-hosted, linux, x64]
#     timeout-minutes: 7
#     steps:
#       - name: ğŸ˜Š checkout
#         uses: actions/checkout@v2
#       - name: ğŸ—ï¸ Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: â˜ï¸ Build Check
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: ./backend/Dockerfile
#           push: false
